// Code generated by goctl. DO NOT EDIT.
package types

type CodeRespose struct {
	CaptchaId string `json:"captchaId"`
	PicPath   string `json:"picPath"`
}

type LoginRequest struct {
	Username    string `json:"username"`
	Password    string `json:"password"`
	CaptchaId   string `json:"captchaId"`
	CaptchaCode string `json:"captchaCode"`
}

type LoginResponse struct {
	AccessToken  string `json:"accessToken"`
	AccessExpire int64  `json:"accessExpire"`
	UserId       int64  `json:"userId"`
	UserName     string `json:"userName"`
}

type ParseExcelRequest struct {
	FileName string `json:"fileName"`
	FilePath string `json:"filePath"`
}

type ParseExcelResponse struct {
}

type RegisterRequest struct {
	Username    string `json:"username"`
	Gender      int64  `json:"gender"`
	Mobile      string `json:"mobile"`
	Password    string `json:"password"`
	CaptchaId   string `json:"captchaId"`
	CaptchaCode string `json:"captchaCode"`
}

type RegisterResponse struct {
	Id       int64  `json:"id"`
	Username string `json:"username"`
	Gender   int64  `json:"gender"`
	Mobile   string `json:"mobile"`
}

type UserInfoResponse struct {
	Id       int64  `json:"id"`
	Username string `json:"username"`
	Gender   int64  `json:"gender"`
	Mobile   string `json:"mobile"`
}
