// Code generated by goctl. DO NOT EDIT.
// Source: dump.proto

package dumpsvc

import (
	"context"

	"qqcc/apps/dump/rpc/types/dump"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	ParserRequest  = dump.ParserRequest
	ParserResponse = dump.ParserResponse

	DumpSvc interface {
		ParserExcel(ctx context.Context, in *ParserRequest, opts ...grpc.CallOption) (*ParserResponse, error)
	}

	defaultDumpSvc struct {
		cli zrpc.Client
	}
)

func NewDumpSvc(cli zrpc.Client) DumpSvc {
	return &defaultDumpSvc{
		cli: cli,
	}
}

func (m *defaultDumpSvc) ParserExcel(ctx context.Context, in *ParserRequest, opts ...grpc.CallOption) (*ParserResponse, error) {
	client := dump.NewDumpSvcClient(m.cli.Conn())
	return client.ParserExcel(ctx, in, opts...)
}
