// Code generated by goctl. DO NOT EDIT.
// Source: product.proto

package productclient

import (
	"context"

	"mall/service/product/rpc/types/product"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	DetailProdRequest  = product.DetailProdRequest
	DetailProdResponse = product.DetailProdResponse
	ProdRequest        = product.ProdRequest
	ProdResponse       = product.ProdResponse
	RemoveProdRequest  = product.RemoveProdRequest
	RemoveProdResponse = product.RemoveProdResponse
	UpdateProdRequest  = product.UpdateProdRequest
	UpdateProdResponse = product.UpdateProdResponse

	Product interface {
		Create(ctx context.Context, in *ProdRequest, opts ...grpc.CallOption) (*ProdResponse, error)
		Update(ctx context.Context, in *UpdateProdRequest, opts ...grpc.CallOption) (*UpdateProdResponse, error)
		Remove(ctx context.Context, in *RemoveProdRequest, opts ...grpc.CallOption) (*RemoveProdResponse, error)
		Detail(ctx context.Context, in *DetailProdRequest, opts ...grpc.CallOption) (*DetailProdResponse, error)
	}

	defaultProduct struct {
		cli zrpc.Client
	}
)

func NewProduct(cli zrpc.Client) Product {
	return &defaultProduct{
		cli: cli,
	}
}

func (m *defaultProduct) Create(ctx context.Context, in *ProdRequest, opts ...grpc.CallOption) (*ProdResponse, error) {
	client := product.NewProductClient(m.cli.Conn())
	return client.Create(ctx, in, opts...)
}

func (m *defaultProduct) Update(ctx context.Context, in *UpdateProdRequest, opts ...grpc.CallOption) (*UpdateProdResponse, error) {
	client := product.NewProductClient(m.cli.Conn())
	return client.Update(ctx, in, opts...)
}

func (m *defaultProduct) Remove(ctx context.Context, in *RemoveProdRequest, opts ...grpc.CallOption) (*RemoveProdResponse, error) {
	client := product.NewProductClient(m.cli.Conn())
	return client.Remove(ctx, in, opts...)
}

func (m *defaultProduct) Detail(ctx context.Context, in *DetailProdRequest, opts ...grpc.CallOption) (*DetailProdResponse, error) {
	client := product.NewProductClient(m.cli.Conn())
	return client.Detail(ctx, in, opts...)
}
