// Code generated by goctl. DO NOT EDIT.
// Source: dump.proto

package dumpClient

import (
	"context"

	"qqcc/apps/dump/rpc/types/dump"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	ParserRequest  = dump.ParserRequest
	ParserResponse = dump.ParserResponse

	Dump interface {
		ParserExcel(ctx context.Context, in *ParserRequest, opts ...grpc.CallOption) (*ParserResponse, error)
	}

	defaultDump struct {
		cli zrpc.Client
	}
)

func NewDump(cli zrpc.Client) Dump {
	return &defaultDump{
		cli: cli,
	}
}

func (m *defaultDump) ParserExcel(ctx context.Context, in *ParserRequest, opts ...grpc.CallOption) (*ParserResponse, error) {
	client := dump.NewDumpClient(m.cli.Conn())
	return client.ParserExcel(ctx, in, opts...)
}
