// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.21.0
// source: rpc/dump.proto

package dump

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// DumpSvcClient is the client API for DumpSvc service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type DumpSvcClient interface {
	ParserExcel(ctx context.Context, in *ParserRequest, opts ...grpc.CallOption) (*ParserResponse, error)
}

type dumpSvcClient struct {
	cc grpc.ClientConnInterface
}

func NewDumpSvcClient(cc grpc.ClientConnInterface) DumpSvcClient {
	return &dumpSvcClient{cc}
}

func (c *dumpSvcClient) ParserExcel(ctx context.Context, in *ParserRequest, opts ...grpc.CallOption) (*ParserResponse, error) {
	out := new(ParserResponse)
	err := c.cc.Invoke(ctx, "/dump.DumpSvc/ParserExcel", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// DumpSvcServer is the server API for DumpSvc service.
// All implementations must embed UnimplementedDumpSvcServer
// for forward compatibility
type DumpSvcServer interface {
	ParserExcel(context.Context, *ParserRequest) (*ParserResponse, error)
	mustEmbedUnimplementedDumpSvcServer()
}

// UnimplementedDumpSvcServer must be embedded to have forward compatible implementations.
type UnimplementedDumpSvcServer struct {
}

func (UnimplementedDumpSvcServer) ParserExcel(context.Context, *ParserRequest) (*ParserResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ParserExcel not implemented")
}
func (UnimplementedDumpSvcServer) mustEmbedUnimplementedDumpSvcServer() {}

// UnsafeDumpSvcServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to DumpSvcServer will
// result in compilation errors.
type UnsafeDumpSvcServer interface {
	mustEmbedUnimplementedDumpSvcServer()
}

func RegisterDumpSvcServer(s grpc.ServiceRegistrar, srv DumpSvcServer) {
	s.RegisterService(&DumpSvc_ServiceDesc, srv)
}

func _DumpSvc_ParserExcel_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ParserRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DumpSvcServer).ParserExcel(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/dump.DumpSvc/ParserExcel",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DumpSvcServer).ParserExcel(ctx, req.(*ParserRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// DumpSvc_ServiceDesc is the grpc.ServiceDesc for DumpSvc service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var DumpSvc_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "dump.DumpSvc",
	HandlerType: (*DumpSvcServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ParserExcel",
			Handler:    _DumpSvc_ParserExcel_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "rpc/dump.proto",
}
