// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.21.0
// source: rpc/dump.proto

package dump

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ParserRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Filename string `protobuf:"bytes,1,opt,name=filename,proto3" json:"filename,omitempty"`
	Filepath string `protobuf:"bytes,2,opt,name=filepath,proto3" json:"filepath,omitempty"`
}

func (x *ParserRequest) Reset() {
	*x = ParserRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rpc_dump_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ParserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ParserRequest) ProtoMessage() {}

func (x *ParserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_dump_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ParserRequest.ProtoReflect.Descriptor instead.
func (*ParserRequest) Descriptor() ([]byte, []int) {
	return file_rpc_dump_proto_rawDescGZIP(), []int{0}
}

func (x *ParserRequest) GetFilename() string {
	if x != nil {
		return x.Filename
	}
	return ""
}

func (x *ParserRequest) GetFilepath() string {
	if x != nil {
		return x.Filepath
	}
	return ""
}

type ParserResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *ParserResponse) Reset() {
	*x = ParserResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rpc_dump_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ParserResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ParserResponse) ProtoMessage() {}

func (x *ParserResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_dump_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ParserResponse.ProtoReflect.Descriptor instead.
func (*ParserResponse) Descriptor() ([]byte, []int) {
	return file_rpc_dump_proto_rawDescGZIP(), []int{1}
}

type FindParserJonRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id int64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *FindParserJonRequest) Reset() {
	*x = FindParserJonRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rpc_dump_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FindParserJonRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FindParserJonRequest) ProtoMessage() {}

func (x *FindParserJonRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_dump_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FindParserJonRequest.ProtoReflect.Descriptor instead.
func (*FindParserJonRequest) Descriptor() ([]byte, []int) {
	return file_rpc_dump_proto_rawDescGZIP(), []int{2}
}

func (x *FindParserJonRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type FindParserJonResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id       int64   `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Filepath string  `protobuf:"bytes,2,opt,name=filepath,proto3" json:"filepath,omitempty"`
	Filesize float64 `protobuf:"fixed64,3,opt,name=filesize,proto3" json:"filesize,omitempty"`
	Mark     string  `protobuf:"bytes,4,opt,name=mark,proto3" json:"mark,omitempty"`
	Resolved bool    `protobuf:"varint,5,opt,name=resolved,proto3" json:"resolved,omitempty"`
	Rows     int64   `protobuf:"varint,6,opt,name=rows,proto3" json:"rows,omitempty"`
}

func (x *FindParserJonResponse) Reset() {
	*x = FindParserJonResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rpc_dump_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FindParserJonResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FindParserJonResponse) ProtoMessage() {}

func (x *FindParserJonResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_dump_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FindParserJonResponse.ProtoReflect.Descriptor instead.
func (*FindParserJonResponse) Descriptor() ([]byte, []int) {
	return file_rpc_dump_proto_rawDescGZIP(), []int{3}
}

func (x *FindParserJonResponse) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *FindParserJonResponse) GetFilepath() string {
	if x != nil {
		return x.Filepath
	}
	return ""
}

func (x *FindParserJonResponse) GetFilesize() float64 {
	if x != nil {
		return x.Filesize
	}
	return 0
}

func (x *FindParserJonResponse) GetMark() string {
	if x != nil {
		return x.Mark
	}
	return ""
}

func (x *FindParserJonResponse) GetResolved() bool {
	if x != nil {
		return x.Resolved
	}
	return false
}

func (x *FindParserJonResponse) GetRows() int64 {
	if x != nil {
		return x.Rows
	}
	return 0
}

type UpdateParserJonRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id       int64   `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Filepath string  `protobuf:"bytes,2,opt,name=filepath,proto3" json:"filepath,omitempty"`
	Filesize float64 `protobuf:"fixed64,3,opt,name=filesize,proto3" json:"filesize,omitempty"`
	Mark     string  `protobuf:"bytes,4,opt,name=mark,proto3" json:"mark,omitempty"`
	Resolved bool    `protobuf:"varint,5,opt,name=resolved,proto3" json:"resolved,omitempty"`
	Rows     int64   `protobuf:"varint,6,opt,name=rows,proto3" json:"rows,omitempty"`
}

func (x *UpdateParserJonRequest) Reset() {
	*x = UpdateParserJonRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rpc_dump_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateParserJonRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateParserJonRequest) ProtoMessage() {}

func (x *UpdateParserJonRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_dump_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateParserJonRequest.ProtoReflect.Descriptor instead.
func (*UpdateParserJonRequest) Descriptor() ([]byte, []int) {
	return file_rpc_dump_proto_rawDescGZIP(), []int{4}
}

func (x *UpdateParserJonRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *UpdateParserJonRequest) GetFilepath() string {
	if x != nil {
		return x.Filepath
	}
	return ""
}

func (x *UpdateParserJonRequest) GetFilesize() float64 {
	if x != nil {
		return x.Filesize
	}
	return 0
}

func (x *UpdateParserJonRequest) GetMark() string {
	if x != nil {
		return x.Mark
	}
	return ""
}

func (x *UpdateParserJonRequest) GetResolved() bool {
	if x != nil {
		return x.Resolved
	}
	return false
}

func (x *UpdateParserJonRequest) GetRows() int64 {
	if x != nil {
		return x.Rows
	}
	return 0
}

type UpdateParserJonResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *UpdateParserJonResponse) Reset() {
	*x = UpdateParserJonResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rpc_dump_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateParserJonResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateParserJonResponse) ProtoMessage() {}

func (x *UpdateParserJonResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_dump_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateParserJonResponse.ProtoReflect.Descriptor instead.
func (*UpdateParserJonResponse) Descriptor() ([]byte, []int) {
	return file_rpc_dump_proto_rawDescGZIP(), []int{5}
}

var File_rpc_dump_proto protoreflect.FileDescriptor

var file_rpc_dump_proto_rawDesc = []byte{
	0x0a, 0x0e, 0x72, 0x70, 0x63, 0x2f, 0x64, 0x75, 0x6d, 0x70, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x12, 0x04, 0x64, 0x75, 0x6d, 0x70, 0x22, 0x47, 0x0a, 0x0d, 0x50, 0x61, 0x72, 0x73, 0x65, 0x72,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1a, 0x0a, 0x08, 0x66, 0x69, 0x6c, 0x65, 0x6e,
	0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x66, 0x69, 0x6c, 0x65, 0x6e,
	0x61, 0x6d, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x66, 0x69, 0x6c, 0x65, 0x70, 0x61, 0x74, 0x68, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x66, 0x69, 0x6c, 0x65, 0x70, 0x61, 0x74, 0x68, 0x22,
	0x10, 0x0a, 0x0e, 0x50, 0x61, 0x72, 0x73, 0x65, 0x72, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x22, 0x26, 0x0a, 0x14, 0x46, 0x69, 0x6e, 0x64, 0x50, 0x61, 0x72, 0x73, 0x65, 0x72, 0x4a,
	0x6f, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x02, 0x69, 0x64, 0x22, 0xa3, 0x01, 0x0a, 0x15, 0x46, 0x69,
	0x6e, 0x64, 0x50, 0x61, 0x72, 0x73, 0x65, 0x72, 0x4a, 0x6f, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52,
	0x02, 0x69, 0x64, 0x12, 0x1a, 0x0a, 0x08, 0x66, 0x69, 0x6c, 0x65, 0x70, 0x61, 0x74, 0x68, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x66, 0x69, 0x6c, 0x65, 0x70, 0x61, 0x74, 0x68, 0x12,
	0x1a, 0x0a, 0x08, 0x66, 0x69, 0x6c, 0x65, 0x73, 0x69, 0x7a, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x01, 0x52, 0x08, 0x66, 0x69, 0x6c, 0x65, 0x73, 0x69, 0x7a, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x6d,
	0x61, 0x72, 0x6b, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6d, 0x61, 0x72, 0x6b, 0x12,
	0x1a, 0x0a, 0x08, 0x72, 0x65, 0x73, 0x6f, 0x6c, 0x76, 0x65, 0x64, 0x18, 0x05, 0x20, 0x01, 0x28,
	0x08, 0x52, 0x08, 0x72, 0x65, 0x73, 0x6f, 0x6c, 0x76, 0x65, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x72,
	0x6f, 0x77, 0x73, 0x18, 0x06, 0x20, 0x01, 0x28, 0x03, 0x52, 0x04, 0x72, 0x6f, 0x77, 0x73, 0x22,
	0xa4, 0x01, 0x0a, 0x16, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x50, 0x61, 0x72, 0x73, 0x65, 0x72,
	0x4a, 0x6f, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x02, 0x69, 0x64, 0x12, 0x1a, 0x0a, 0x08, 0x66, 0x69,
	0x6c, 0x65, 0x70, 0x61, 0x74, 0x68, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x66, 0x69,
	0x6c, 0x65, 0x70, 0x61, 0x74, 0x68, 0x12, 0x1a, 0x0a, 0x08, 0x66, 0x69, 0x6c, 0x65, 0x73, 0x69,
	0x7a, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x01, 0x52, 0x08, 0x66, 0x69, 0x6c, 0x65, 0x73, 0x69,
	0x7a, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x6d, 0x61, 0x72, 0x6b, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x04, 0x6d, 0x61, 0x72, 0x6b, 0x12, 0x1a, 0x0a, 0x08, 0x72, 0x65, 0x73, 0x6f, 0x6c, 0x76,
	0x65, 0x64, 0x18, 0x05, 0x20, 0x01, 0x28, 0x08, 0x52, 0x08, 0x72, 0x65, 0x73, 0x6f, 0x6c, 0x76,
	0x65, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x72, 0x6f, 0x77, 0x73, 0x18, 0x06, 0x20, 0x01, 0x28, 0x03,
	0x52, 0x04, 0x72, 0x6f, 0x77, 0x73, 0x22, 0x19, 0x0a, 0x17, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65,
	0x50, 0x61, 0x72, 0x73, 0x65, 0x72, 0x4a, 0x6f, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x32, 0xde, 0x01, 0x0a, 0x04, 0x44, 0x75, 0x6d, 0x70, 0x12, 0x38, 0x0a, 0x0b, 0x50, 0x61,
	0x72, 0x73, 0x65, 0x72, 0x45, 0x78, 0x63, 0x65, 0x6c, 0x12, 0x13, 0x2e, 0x64, 0x75, 0x6d, 0x70,
	0x2e, 0x50, 0x61, 0x72, 0x73, 0x65, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x14,
	0x2e, 0x64, 0x75, 0x6d, 0x70, 0x2e, 0x50, 0x61, 0x72, 0x73, 0x65, 0x72, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x12, 0x4c, 0x0a, 0x11, 0x46, 0x69, 0x6e, 0x64, 0x50, 0x61, 0x72, 0x73,
	0x65, 0x72, 0x4a, 0x6f, 0x62, 0x42, 0x79, 0x49, 0x64, 0x12, 0x1a, 0x2e, 0x64, 0x75, 0x6d, 0x70,
	0x2e, 0x46, 0x69, 0x6e, 0x64, 0x50, 0x61, 0x72, 0x73, 0x65, 0x72, 0x4a, 0x6f, 0x6e, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1b, 0x2e, 0x64, 0x75, 0x6d, 0x70, 0x2e, 0x46, 0x69, 0x6e,
	0x64, 0x50, 0x61, 0x72, 0x73, 0x65, 0x72, 0x4a, 0x6f, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x12, 0x4e, 0x0a, 0x0f, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x50, 0x61, 0x72, 0x73,
	0x65, 0x72, 0x4a, 0x6f, 0x62, 0x12, 0x1c, 0x2e, 0x64, 0x75, 0x6d, 0x70, 0x2e, 0x55, 0x70, 0x64,
	0x61, 0x74, 0x65, 0x50, 0x61, 0x72, 0x73, 0x65, 0x72, 0x4a, 0x6f, 0x6e, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x1a, 0x1d, 0x2e, 0x64, 0x75, 0x6d, 0x70, 0x2e, 0x55, 0x70, 0x64, 0x61, 0x74,
	0x65, 0x50, 0x61, 0x72, 0x73, 0x65, 0x72, 0x4a, 0x6f, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x42, 0x08, 0x5a, 0x06, 0x2e, 0x2f, 0x64, 0x75, 0x6d, 0x70, 0x62, 0x06, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_rpc_dump_proto_rawDescOnce sync.Once
	file_rpc_dump_proto_rawDescData = file_rpc_dump_proto_rawDesc
)

func file_rpc_dump_proto_rawDescGZIP() []byte {
	file_rpc_dump_proto_rawDescOnce.Do(func() {
		file_rpc_dump_proto_rawDescData = protoimpl.X.CompressGZIP(file_rpc_dump_proto_rawDescData)
	})
	return file_rpc_dump_proto_rawDescData
}

var file_rpc_dump_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_rpc_dump_proto_goTypes = []interface{}{
	(*ParserRequest)(nil),           // 0: dump.ParserRequest
	(*ParserResponse)(nil),          // 1: dump.ParserResponse
	(*FindParserJonRequest)(nil),    // 2: dump.FindParserJonRequest
	(*FindParserJonResponse)(nil),   // 3: dump.FindParserJonResponse
	(*UpdateParserJonRequest)(nil),  // 4: dump.UpdateParserJonRequest
	(*UpdateParserJonResponse)(nil), // 5: dump.UpdateParserJonResponse
}
var file_rpc_dump_proto_depIdxs = []int32{
	0, // 0: dump.Dump.ParserExcel:input_type -> dump.ParserRequest
	2, // 1: dump.Dump.FindParserJobById:input_type -> dump.FindParserJonRequest
	4, // 2: dump.Dump.UpdateParserJob:input_type -> dump.UpdateParserJonRequest
	1, // 3: dump.Dump.ParserExcel:output_type -> dump.ParserResponse
	3, // 4: dump.Dump.FindParserJobById:output_type -> dump.FindParserJonResponse
	5, // 5: dump.Dump.UpdateParserJob:output_type -> dump.UpdateParserJonResponse
	3, // [3:6] is the sub-list for method output_type
	0, // [0:3] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_rpc_dump_proto_init() }
func file_rpc_dump_proto_init() {
	if File_rpc_dump_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_rpc_dump_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ParserRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rpc_dump_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ParserResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rpc_dump_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FindParserJonRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rpc_dump_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FindParserJonResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rpc_dump_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdateParserJonRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rpc_dump_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdateParserJonResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_rpc_dump_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_rpc_dump_proto_goTypes,
		DependencyIndexes: file_rpc_dump_proto_depIdxs,
		MessageInfos:      file_rpc_dump_proto_msgTypes,
	}.Build()
	File_rpc_dump_proto = out.File
	file_rpc_dump_proto_rawDesc = nil
	file_rpc_dump_proto_goTypes = nil
	file_rpc_dump_proto_depIdxs = nil
}
