Name: product.rpc
ListenOn: 0.0.0.0:19002
Etcd:
  Hosts:
  - 127.0.0.1:12379
  Key: product.rpc
Mysql:
  DataSource: root:root@tcp(mysql:13316)/mall?charset=utf8mb4&parseTime=true&loc=Asia%2FShanghai

CacheRedis:
  - Host: redis:6379
    Type: node
    Pass:
