global:
  scrape_interval:
  external_labels:
    monitor: 'codelab-monitor'

scrape_configs:
  - job_name: 'prometheus'
    scrape_interval: 5s  #global catch time
    static_configs:
      - targets: ['localhost:9090']
  # bff服务监控
  - job_name: 'bff-api'
    static_configs:
      # 目标的采集地址
      - targets: ["host.docker.internal:9110"]
        labels:
          # 自定义标签
          job: bff-api
          app: bff-api
          env: dev
  - job_name: 'user-rpc'
    static_configs:
      # 目标的采集地址
      - targets: ["host.docker.internal:9111"]
        labels:
          # 自定义标签
          job: user-rpc
          app: user-rpc
          env: dev
  # dump服务监控
  - job_name: 'dump-rpc'
    static_configs:
      # 目标的采集地址
      - targets: ["host.docker.internal:9112"]
        labels:
          # 自定义标签
          job: dump-rpc
          app: dump-rpc
          env: dev
  # dump服务监控
  - job_name: 'dump-mq'
    static_configs:
      # 目标的采集地址
      - targets: ["host.docker.internal:9113"]
        labels:
          # 自定义标签
          job: dump-mq
          app: dump-mq
          env: dev

#  - job_name: 'order-api'
#    static_configs:
#      - targets: [ 'looklook:4001' ]
#        labels:
#          job: order-api
#          app: order-api
#          env: dev
#  - job_name: 'order-rpc'
#    static_configs:
#      - targets: [ 'looklook:4002' ]
#        labels:
#          job: order-rpc
#          app: order-rpc
#          env: dev
#  - job_name: 'order-mq'
#    static_configs:
#      - targets: [ 'looklook:4003' ]
#        labels:
#          job: order-mq
#          app: order-mq
#          env: dev
#  - job_name: 'payment-api'
#    static_configs:
#      - targets: [ 'looklook:4004' ]
#        labels:
#          job: payment-api
#          app: payment-api
#          env: dev
#  - job_name: 'payment-rpc'
#    static_configs:
#      - targets: [ 'looklook:4005' ]
#        labels:
#          job: payment-rpc
#          app: payment-rpc
#          env: dev
#  - job_name: 'travel-api'
#    static_configs:
#      - targets: [ 'looklook:4006' ]
#        labels:
#          job: travel-api
#          app: travel-api
#          env: dev
#  - job_name: 'travel-rpc'
#    static_configs:
#      - targets: [ 'looklook:4007' ]
#        labels:
#          job: travel-rpc
#          app: travel-rpc
#          env: dev
#  - job_name: 'usercenter-api'
#    static_configs:
#      - targets: ['looklook:4008']
#        labels:
#          job: usercenter-api
#          app: usercenter-api
#          env: dev
#  - job_name: 'usercenter-rpc'
#    static_configs:
#      - targets: ['looklook:4009']
#        labels:
#          job: usercenter-rpc
#          app: usercenter-rpc
#          env: dev
#  - job_name: 'mqueue-job'
#    static_configs:
#      - targets: [ 'looklook:4010' ]
#        labels:
#          job: mqueue-job
#          app: mqueue-job
#          env: dev
#  - job_name: 'mqueue-scheduler'
#    static_configs:
#      - targets: [ 'looklook:4011' ]
#        labels:
#          job: mqueue-scheduler
#          app: mqueue-scheduler
#          env: dev

