// Code generated by goctl. DO NOT EDIT.
// Source: dump.proto

package server

import (
	"context"

	"qqcc/apps/dump/rpc/internal/logic"
	"qqcc/apps/dump/rpc/internal/svc"
	"qqcc/apps/dump/rpc/types/dump"
)

type DumpSvcServer struct {
	svcCtx *svc.ServiceContext
	dump.UnimplementedDumpSvcServer
}

func NewDumpSvcServer(svcCtx *svc.ServiceContext) *DumpSvcServer {
	return &DumpSvcServer{
		svcCtx: svcCtx,
	}
}

func (s *DumpSvcServer) ParserExcel(ctx context.Context, in *dump.ParserRequest) (*dump.ParserResponse, error) {
	l := logic.NewParserExcelLogic(ctx, s.svcCtx)
	return l.ParserExcel(in)
}
