// Code generated by goctl. DO NOT EDIT.
// Source: dump.proto

package server

import (
	"context"

	"qqcc/apps/dump/rpc/internal/logic"
	"qqcc/apps/dump/rpc/internal/svc"
	"qqcc/apps/dump/rpc/types/dump"
)

type DumpServer struct {
	svcCtx *svc.ServiceContext
	dump.UnimplementedDumpServer
}

func NewDumpServer(svcCtx *svc.ServiceContext) *DumpServer {
	return &DumpServer{
		svcCtx: svcCtx,
	}
}

func (s *DumpServer) ParserExcel(ctx context.Context, in *dump.ParserRequest) (*dump.ParserResponse, error) {
	l := logic.NewParserExcelLogic(ctx, s.svcCtx)
	return l.ParserExcel(in)
}
